def manual():
    print('\33[36;1m_____________________________________________________________________________\33[m\n') 
    print('\33[32;1m                             Manual de Uso')
    print('\33[36;1m_____________________________________________________________________________\33[m\n\n')
    print('\33[32;1m                         Fale a Função Desejada \n                         Para o Boobi Reconhecer.\n\n')
    print('\33[36;1m_____________________________________________________________________________\33[m\n')
    print(f'                                  \33[42;1m MENU \33[m \n\n')
    print("         \33[32;1m1. Manual                                 9.Abrir Visual Code \33[m")
    print("         \33[32;1m2. Alternar Janela                        10.Ligar/Apagar Teclado")
    print("         \33[32;1m3. Abrir Mensageiro                       11.Avançar Video\33[m ")
    print("         \33[32;1m4. Abrir Discord                          12.Retroceder Video\33[m") 
    print("         \33[32;1m5. Abrir Calculadora                      13.Pausar/Reproduzir Video\33[m")
    print("         \33[32;1m6. Próxima Música                         14.Música Anterior\33[m")
    print("         \33[32;1m7. Pausar/Reproduzir Video                15.BIp\33[m")
    print("         \33[32;1m8. Parar/Reproduzir Música                16.Sair\33[m\n\n")
